export const Products = [
  {
    "id": 1,
    "name": "Training fitness gum",
    "price": "15$",
    "department": "Cardio",
    "img":"./img/gum_one.png",
  },
  {
    "id": 2,
    "name": "Training fitness gum",
    "price": "25$",
    "department": "Cardio",
    "img":"./img/gum_two.png",
  },
  {
    "id": 3,
    "name": "Training fitness gum",
    "price": "23$",
    "department": "Cardio",
    "img":"./img/gum_three.png",
  },
  {
    "id": 4,
    "name": "Fat burner",
    "price": "30$",
    "department": "Fat burners",
    "img":"./img/fatburner_one.png",
  },
  {
    "id": 5,
    "name": "Fat burner",
    "price": "35$",
    "department": "Fat burners",
    "img":"./img/fatburner_two.png",
  },
  {
    "id": 6,
    "name": "Fat burner",
    "price": "28$",
    "department": "Fat burners",
    "img":"./img/fatburner_three.png",
  },
  {
    "id": 7,
    "name": "Gloves for fitness",
    "price": "7$",
    "department": "Gloves",
    "img":"./img/gloves_one.png",
  },
  {
    "id": 8,
    "name": "Gloves for fitness",
    "price": "15$",
    "department": "Gloves",
    "img":"./img/gloves_two.png",
  },
  {
    "id": 9,
    "name": "Gloves for fitness",
    "price": "9$",
    "department": "Gloves",
    "img":"./img/gloves_three.png",
  },
  {
    "id": 10,
    "name": "Bottle for water",
    "price": "8$",
    "department": "Bottles",
    "img":"./img/bottle_one.jpg",
  },
  {
    "id": 11,
    "name": "Bottle for water",
    "price": "18$",
    "department": "Bottles",
    "img":"./img/bottle_two.png",
  },
  {
    "id": 12,
    "name": "Bottle for water",
    "price": "10$",
    "department": "Bottles",
    "img":"./img/bottle_three.jpg",
  },
  {
    "id": 13,
    "name": "Protein",
    "price": "20$",
    "department": "Proteins",
    "img":"./img/protein_one.png",
  },
  {
    "id": 14,
    "name": "Protein",
    "price": "18$",
    "department": "Proteins",
    "img":"./img/protein_two.png",
  },
  {
    "id": 15,
    "name": "Protein",
    "price": "27$",
    "department": "Proteins",
    "img":"./img/protein_three.png",
  },
  {
    "id": 16,
    "name": "Sport bag",
    "price": "40$",
    "department": "Sports bags",
    "img":"./img/bag_one.jpg",
  },
  {
    "id": 17,
    "name": "Sport bag",
    "price": "37$",
    "department": "Sports bags",
    "img":"./img/bag_two.png",
  },
  {
    "id": 16,
    "name": "Sport bag",
    "price": "34$",
    "department": "Sports bags",
    "img":"./img/bag_three.png",
  },
  {
    "id": 17,
    "name": "Bandage",
    "price": "6$",
    "department": "Bandages",
    "img":"./img/bandeges_one.png",
  },
  {
    "id": 18,
    "name": "Bandage",
    "price": "9$",
    "department": "Bandages",
    "img": "./img/bandeges_two.png",
  },
  {
    "id": 19,
    "name": "Bandage",
    "price": "3$",
    "department": "Bandages",
    "img":"./img/bandeges_three.png",
  },
]